const ActivityEvent = require("../models/ActivityEvent");

/**
 * Audit Export Service
 * Generates security audit reports in CSV and Markdown formats.
 */
class AuditExportService {
    
    /**
     * Generates a CSV string of activity events for a user.
     */
    static async generateCsv(userId, filter = {}) {
        const events = await ActivityEvent.find({ ...filter, userId }).sort({ createdAt: -1 });
        
        const headers = ["ID", "Timestamp", "Type", "Wallet", "Risk Score", "Actions"];
        const rows = events.map(e => [
            e._id,
            e.createdAt.toISOString(),
            e.type,
            e.walletAddress || "N/A",
            e.riskScore !== null ? e.riskScore : "N/A",
            JSON.stringify(e.metadata || {}).replace(/"/g, '""')
        ]);

        const csvContent = [
            headers.join(","),
            ...rows.map(row => row.map(cell => `"${cell}"`).join(","))
        ].join("\n");

        return csvContent;
    }

    /**
     * Generates a Markdown report of activity events.
     */
    static async generateMarkdown(userEmail, filter = {}) {
        const events = await ActivityEvent.find(filter).sort({ createdAt: -1 }).limit(100);
        
        let md = `# LifeVault Security Audit Log\n`;
        md += `**Target Account:** ${userEmail}\n`;
        md += `**Export Date:** ${new Date().toLocaleString()}\n\n`;
        
        md += `| Timestamp | Event Type | Risk | Details |\n`;
        md += `| :--- | :--- | :--- | :--- |\n`;
        
        events.forEach(e => {
            const risk = e.riskScore !== null ? (e.riskScore * 100).toFixed(0) + "%" : "-";
            md += `| ${e.createdAt.toISOString().split('T')[0]} | ${e.type} | ${risk} | ${e.action || "System Event"} |\n`;
        });

        md += `\n---\n*Securely generated by LifeVault AI Engine*`;
        return md;
    }
}

module.exports = { AuditExportService };
