const { PhishingResult } = require("../models/PhishingResult");
const { User } = require("../models/User");

/**
 * Report Service
 * Generates automated security insights and monthly threat reports.
 */
class ReportService {
    
    /**
     * Generates a monthly security report in Markdown format for a user.
     */
    static async generateMonthlyReport(userId) {
        const user = await User.findById(userId);
        if (!user) throw new Error("User not found");

        const startOfMonth = new Date();
        startOfMonth.setDate(1);
        startOfMonth.setHours(0, 0, 0, 0);

        const results = await PhishingResult.find({
            userId,
            analyzedAt: { $gte: startOfMonth }
        }).sort({ analyzedAt: -1 });

        const totalScans = results.length;
        const criticalThreats = results.filter(r => r.riskLevel === "CRITICAL").length;
        const highRiskThreats = results.filter(r => r.riskLevel === "HIGH").length;

        const reportMd = `
# LifeVault Security Report — ${new Date().toLocaleString('default', { month: 'long', year: 'numeric' })}
**Account Protection Digest for ${user.email}**

## Monthly Summary
- **Total Scans Performed:** ${totalScans}
- **Critical Threats Blocked:** ${criticalThreats}
- **High Risk Alerts:** ${highRiskThreats}
- **Safety Rating:** ${this.calculateSafetyRating(results)}

## Top Targeted Domains
${this.summarizeDomains(results)}

## Security Recommendations
- ${criticalThreats > 0 ? "⚠️ We blocked multiple critical threats. Ensure your Wallet Recovery phrase is NEVER stored on this device." : "✅ No critical threats reached your account this month."}
- ${totalScans < 5 ? "💡 Proactive scanning is low. Use the LifeVault Browser Extension for real-time coverage." : "✅ Good scanning hygiene maintained."}
- Ensure MFA is enabled on all connected financial accounts.

---
*Generated by LifeVault AI Guardian*
        `;

        return {
            metadata: {
                month: startOfMonth.getMonth() + 1,
                year: startOfMonth.getFullYear(),
                generatedAt: new Date().toISOString()
            },
            content: reportMd,
            stats: { totalScans, criticalThreats, highRiskThreats }
        };
    }

    static calculateSafetyRating(results) {
        if (results.length === 0) return "Unknown (Insufficient Data)";
        const criticals = results.filter(r => r.riskLevel === "CRITICAL").length;
        if (criticals > 5) return "AT RISK";
        if (criticals > 0) return "GUARDED";
        return "OPTIMAL";
    }

    static summarizeDomains(results) {
        const domains = results
            .filter(r => r.inputUrl)
            .map(r => new URL(r.inputUrl).hostname);
        
        const counts = {};
        domains.forEach(d => counts[d] = (counts[d] || 0) + 1);
        
        return Object.entries(counts)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5)
            .map(([d, c]) => `- ${d} (${c} attempts)`)
            .join("\n") || "No domain data available.";
    }
}

module.exports = { ReportService };
