const { FeatureFlagService, requireFeature } = require("../services/featureFlagService");

const success = (res, data) => res.json({ status: "success", data });

/**
 * POST /api/v1/zk/verify-identity
 * Verify a ZK identity proof generated by the user's browser/extension.
 */
router.post("/verify-identity", auth, requireFeature("ZK_IDENTITY_VERIFICATION"), async (req, res) => {
    try {
        const { proof, publicSignals } = req.body;
        
        if (!proof || !publicSignals) {
            return res.status(400).json({ error: "Proof and Public Signals required" });
        }

        const isValid = await ZkService.verifyIdentityProof(proof, publicSignals);
        
        if (isValid) {
            // Mark user as ZK-Verified in their session or DB
            // req.user.isZkVerified = true;
            return success(res, { verified: true, message: "Zero-Knowledge Identity Proof Confirmed" });
        } else {
            return res.status(403).json({ status: "error", message: "Invalid ZK Proof" });
        }
    } catch (error) {
        return res.status(500).json({ status: "error", message: error.message });
    }
});

module.exports = router;
